= Ansible Bootcamp Enablement

Site content for the Ansible Bootcamp Enablement.

== Getting Started

=== Understanding the Basic Template Directory Structure

[source,sh]
----
./bootcamp-content # Location where all code for the bootcamp is stored
├── <lab-module>.                    # Lab Module Directory
│   └── <content>                    # Associated content for the lab
./documentation/modules/ROOT/
├── assets
│   └── images                       # Images used in your content
│       └── <lab-module>             # Lab Module Directory
│           └── example-image.png    # Images
├── nav.adoc                         # Navigation for your lab
├── pages                            # Your content goes here
│   ├── index.adoc                   # First page of your lab, e.g. overview etc
│   └── <lab-module>                 # Lab Module Directory
│       └── 01-lab-1.adoc            # Lab 1 content
└── partials                         # You can add partials here, reusable content inserted inline into your modules
    └── example_partial.adoc
----

=== Using ETX-Ansible DevSpaces

Once you have a lab environment set up, you can use DevSpaces to develop additional content. To do this you should first access your devspace environment by clicking the 9 square icon in the top right of the console and clicking, "Red Hat OpenShift DevSpaces".

If it is your first time using this cluster's devspaces you will need to authorize oauth for DevSpaces. Then in the top right drop down next to your username and icon and select, "User Preferences". In the User Preferences page you will want to select "Personal Access Tokens" and add a Github Accerss token. See creating a Github Personal Access Token section below.

Once you re-authenticate to devspaces you can paste in the repository for this repo under the "Import from Git" section into the "Git repo URL" box. Then click the "Create & Open" button. This will launch your developer workspace.

==== Launching antora to view content

. Inside your Developer Workspace (browser based vscode) click the hamburger icon in the top left
. Hover over "Terminal" in the menu that pops up
. Click on "Run Task..."
. Select 'devfile' from the menu that pops up
. Click on 'devfile: start-antora'

You will see a terminal start and launch antora using podman. A pop-up will show to notify you that it has exposed a website and will ask you if you want to view it. Open that site and it will redirect you to the documentation site.

There are additional devfile tasks available to stop and restart the pandora container.

==== Creating a github Personal Access Token

. Log into your GitHub account
. Click on your profile avatar, and select "Settings."
. In the left sidebar, scroll down and click on "Developer settings."
. Click on "Personal access tokens" and then choose "Tokens (classic)" or "Fine-grained tokens" depending on your needs. For most Dev Spaces integrations, classic tokens are sufficient.
. Click on "Generate new token" (or "Generate new token (classic)" if you selected classic tokens).
. Configure Token Details

    Note: Provide a descriptive name for your token.
    Expiration: Set an expiration date for the token. For security, it is recommended to set a reasonable expiration.
    Scopes: Select the necessary permissions (scopes) for the token. For accessing private repositories, the repo scope (or more granular fine-grained permissions) is typically required.

. Click "Generate token."
. Immediately copy the generated token. It will only be displayed once and cannot be retrieved again. Store it securely.

=== Using Containers (Recommended)

In order to test and develop on your local machine, you can use a specially built container with Podman or Docker as follows.

. Create a git repo from this template
.. Suggested naming: `showroom_<lab-name>`
. Clone your new repo and `cd` into it
. When you make changes to the content, all you need is to kill the container and run it again.
+
[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

For SELinux environments, `:z` may need to be appended to the volume mount:

----
podman run --rm --name antora -v $PWD:/antora:z -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

Live-reload is not supported.
