= Automation Developer Experience 

This lab walks through some of the basic software development pratices as they apply to automation development. All automation files should be treated as code. This means scanning for code syntax and quality, checking for secrets, and testing your code as much as possible before committing it. Once it is in git, consider it public and without effort will be there forever. 

== Git

While technically you can use something like a local directory for AAP, in general consider `git` a requirement. Furthermore, to properly scale automation across an enterprise, `git` _proficiency_ is required. This lab covers the extreme basics of `git`. For many of you, this may be 

=== CLI Completion

While not required, sourcing these two files will greatly improve your CLI interactions. Note that this can also be added to the `devfile` or a local `.bashrc`

[source,bash]
----
source /usr/share/bash-completion/completions/git
source /usr/share/git-core/contrib/completion/git-prompt.sh
PS1='[\u \W$(__git_ps1 " (%s)")]\$ '
----

Notice your prompt will now display which branch you are in. Also, `git` sub commands now auto-complete with the TAB key.

=== Set Global Settings

If you haven't done so already in this Ansible Workspace, set your global username and email:

[user devspaces-example (main)]$

[source,bash]
----
[user devspaces-example (main)]$ git config --global user.name "First Last"
[user devspaces-example (main)]$ git config --global user.email "email@example.com"
----

=== Branches

Branches should be used liberally. Test ideas and have no fear trashing a branch that didn't work. It's better to leave a branch is it is and start a new one based on your current working branch rather than testing a few things and reverting the commits or comment/uncomment things.

[source,bash]
----
[user devspaces-example (main)]$ git branch
* main
[user devspaces-example (main)]$ git branch test
[user devspaces-example (main)]$ git branch
* main
  test
[user devspaces-example (main)]$ git checkout test
A       secret
Switched to branch 'test'
[user devspaces-example (test)]$ git branch
  main
* test
----

=== Pull/Merge Requests

Pull/Merge requests are when you have work in a branch you want to merge into another branch. Typically this is a feature branch with your work that you want to merge into `main` but it could be any other branch target. PR/MRs are an essential way to review code and allow others to comment and provide feedback or changes. PR/MRs can also be used to kick off pipelines to run further commands on this branch of code.

=== Merge conflicts

When a change is detected on the same line and git is unable to automtically apply the changes, human intervention is needed.

=== Updating branches

When working in a branch, it is often necessary to ensure your branch has the latest commits that are in main. If it has been a while since you created or updated your branch, it could be several commits behind. 

_Merge_ will take two divergent branches and preserve their history, adding a commit to tie them together

_Rebase_ will rewind and play commits back in order resulting in a cleaner, more linear history, but can make merge conflicts more difficult to manage

=== Cleaning up git history

While you generally should not be editing git history, there are times where this is necessary. Perhaps commits were made with a default or incorrect `user.name` or `user.email` and needed to be corrected. Or perhaps secrets were leaked and though cleaned up in HEAD, they are still in git history. In these cases, it is possible to edit specific commits.

== Secrets Scanning 

It is absolutely vital that you never EVER commit any secrets to git. Even if you revert the commit or delete the file, it is still in history. Even if it is "just a lab server" or "only internal" a secret will trigger many security scans requiring additinal work to explain if it is valid and needs rotating or not. Just don't do it. This lab will walk through using a tool like `gitleaks` to help keep your secrets out of git.

First create a fake API-like key. The default regex and patterns will determine a UUID-like value to be similar to an API key:

[source,bash]
----
$ cd /projects/devspaces-example/
$ echo key=$(uuidgen) > secret
$ cat secret
key=3863b2c6-cc7b-4832-92b6-5b82d6b1a987
----

None of these specifics matter, but feel free to add additional files in this directory with any kind of desired data, the next step will scan the entire directory.

[source,bash]
----
$ podman pull docker.io/zricethezav/gitleaks:latest
Trying to pull docker.io/zricethezav/gitleaks:latest...
Getting image source signatures
Copying blob 91da3791a8e8 done   | 
Copying blob daed8b4062ea done   | 
Copying blob e590f02e913a done   | 
Copying blob 1747dece9491 done   | 
Copying config 49c41c2292 done   | 
Writing manifest to image destination
49c41c2292e05b683dd2dbbe7f7677ca397722f1f0364adf615a3a6913f71ade
----

Run `gitleaks` to scan the directory containing the generated fake secret:

[source,bash]
----
$ podman run -v /projects/devspaces-example/:/scan:Z zricethezav/gitleaks:latest dir -v /scan/

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

Finding:     key=3863b2c6-cc7b-4832-92b6-5b82d6b1a987
Secret:      3863b2c6-cc7b-4832-92b6-5b82d6b1a987
RuleID:      generic-api-key
Entropy:     3.583275
File:        /scan/secret
Line:        1
Fingerprint: /scan/secret:generic-api-key:1

1:43AM INF scanned ~15523 bytes (15.52 KB) in 10.9ms
1:43AM WRN leaks found: 1
----

The default rules should detect the UUID as an API key.

== Pre-Commit

Pre-commit is a tool that essentially hooks into `git` and runs additional tooling before the commit actualy writes to git history. This is a perfect way to automatically call things like `ansible-lint` and `gitleaks` before having to go back and squash or clean up git history.

Install pre-commit:

[source,bash]
----
$ pip install --user pre-commit
----

[source,bash]
----
Collecting pre-commit
  Downloading pre_commit-4.3.0-py2.py3-none-any.whl (220 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.0/221.0 kB 26.4 MB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Downloading cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
Collecting identify>=1.0.0
  Downloading identify-2.6.15-py2.py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 63.9 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.9.1-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib64/python3.11/site-packages (from pre-commit) (6.0.3)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.11/site-packages (from pre-commit) (20.25.1)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.11/site-packages (from virtualenv>=20.10.0->pre-commit) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in /usr/local/lib/python3.11/site-packages (from virtualenv>=20.10.0->pre-commit) (3.13.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.11/site-packages (from virtualenv>=20.10.0->pre-commit) (4.2.0)
Installing collected packages: nodeenv, identify, cfgv, pre-commit
  WARNING: The script nodeenv is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script identify-cli is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pre-commit is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cfgv-3.4.0 identify-2.6.15 nodeenv-1.9.1 pre-commit-4.3.0
----

Notice the *WARNING:* this tells you the path the binary was installed to.

Add the following to `.pre-commit-config.yaml`:

[source,bash]
----
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0 # Use the desired Gitleaks version
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: podman run -v /projects/devspaces-example:/scan:Z zricethezav/gitleaks:latest dir -v /scan/
        language: system # Indicate that it's a system command (Podman)
        stages: [pre-commit]
----

Install the pre-commit hook:

[source,bash]
----
$ /home/user/.local/bin/pre-commit install

 pre-commit installed at .git/hooks/pre-commit
----

Attempt a `git commit` which should fail:

[source,bash]
----
$ git add secret
$ git commit

gitleaks.................................................................Failed
- hook id: gitleaks
- exit code: 1

○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

Finding:     key=3863b2c6-cc7b-4832-92b6-5b82d6b1a987
Secret:      3863b2c6-cc7b-4832-92b6-5b82d6b1a987
RuleID:      generic-api-key
Entropy:     3.583275
File:        /gitleaks/secret
Line:        1
Fingerprint: /gitleaks/secret:generic-api-key:1

1:22AM INF scanned ~15523 bytes (15.52 KB) in 7.62ms
1:22AM WRN leaks found: 1

bash-5.1$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   secret

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .pre-commit-config.yaml

----

In this way a developer never needs to remember to run a tool before a commit, pre-commit will do it for you, keeping mistakes out of git history.

== Ansible Development Tools (ADT)

Overview, source page: https://ansible.readthedocs.io/projects/dev-tools/

The curated list of tools installed as part of the Ansible automation developer tools package includes:

ansible-core: Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems.

ansible-builder: a utility for building Ansible execution environments.

ansible-creator: a utility for scaffolding Ansible projects and content with leading practices.

ansible-lint: a utility to identify and correct stylistic errors and anti-patterns in Ansible playbooks and roles.

ansible-navigator a text-based user interface (TUI) for developing and troubleshooting Ansible content with execution environments.

ansible-sign: a utility for signing and verifying Ansible content.

molecule: Molecule aids in the development and testing of Ansible content: collections, playbooks and roles

pytest-ansible: a pytest testing framework extension that provides additional functionality for testing Ansible module and plugin Python code.

tox-ansible: an extension to the tox testing utility that provides additional functionality to check Ansible module and plugin Python code under different Python interpreters and Ansible core versions.

ansible-dev-environment: a utility for building and managing a virtual environment for Ansible content development.
