= Automation Developer Experience 

This lab walks through some of the basic software development pratices as they apply to automation development. All automation files should be treated as code. This means scanning for code syntax and quality, checking for secrets, and testing your code as much as possible before committing it. Once it is in git, consider it public and without effort will be there forever. 

== Git

While technically you can use something like a local directory for AAP, in general consider `git` a requirement. Furthermore, to properly scale automation across an enterprise, `git` _proficiency_ is required. This lab covers the extreme basics of `git`. For many of you, this may be 

=== CLI Completion

While not required, sourcing these two files will greatly improve your CLI interactions. Note that this can also be added to the `devfile` or a local `.bashrc`

[source,bash]
----
source /usr/share/bash-completion/completions/git
source /usr/share/git-core/contrib/completion/git-prompt.sh
PS1='[\u \W$(__git_ps1 " (%s)")]\$ '
----

Notice your prompt will now display which branch you are in. Also, `git` sub commands now auto-complete with the TAB key.

=== Set Global Settings

If you haven't done so already in this Ansible Workspace, set your global username and email:

[source,bash]
----
git config --global user.name "First Last"
git config --global user.email "email@example.com"
----

=== Branches

Branches should be used liberally. Test ideas and have no fear trashing a branch that didn't work. It's better to leave a branch is it is and start a new one based on your current working branch rather than testing a few things and reverting the commits or comment/uncomment things.

[source,bash]
----
git branch
git branch test
git checkout test
git branch
----

=== Pull/Merge Requests

Pull/Merge requests are when you have work in a branch you want to merge into another branch. Typically this is a feature branch with your work that you want to merge into `main` but it could be any other branch target. PR/MRs are an essential way to review code and allow others to comment and provide feedback or changes. PR/MRs can also be used to kick off pipelines to run further commands on this branch of code.

=== Merge conflicts

When a change is detected on the same line and git is unable to automtically apply the changes, human intervention is needed.

=== Updating branches

When working in a branch, it is often necessary to ensure your branch has the latest commits that are in main. If it has been a while since you created or updated your branch, it could be several commits behind. 

_Merge_ will take two divergent branches and preserve their history, adding a commit to tie them together

_Rebase_ will rewind and play commits back in order resulting in a cleaner, more linear history, but can make merge conflicts more difficult to manage

=== Cleaning up git history

While you generally should not be editing git history, there are times where this is necessary. Perhaps commits were made with a default or incorrect `user.name` or `user.email` and needed to be corrected. Or perhaps secrets were leaked and though cleaned up in HEAD, they are still in git history. In these cases, it is possible to edit specific commits.

== Secrets Scanning 

It is absolutely vital that you never EVER commit any secrets to git. Even if you revert the commit or delete the file, it is still in history. Even if it is "just a lab server" or "only internal" a secret will trigger many security scans requiring additinal work to explain if it is valid and needs rotating or not. Just don't do it. This lab will walk through using a tool like `gitleaks` to help keep your secrets out of git.

First create a fake API-like key. The default regex and patterns will determine a UUID-like value to be similar to an API key:

[source,bash]
----
cd /projects
mkdir leak_test
echo key=$(uuidgen) > leak_test/file
cat leak_test/file
----

None of these specifics matter, but feel free to add additional files in this directory with any kind of desired data, the next step will scan the entire directory.

[source,bash]
----
podman pull docker.io/zricethezav/gitleaks:latest
podman run -v /projects/leak_test/:/scan:Z zricethezav/gitleaks:latest dir -v /scan/
----

The default rules should detect the UUID as an API key.

== Pre-Commit

Pre-commit is a tool that essentially hooks into `git` and runs additional tooling before the commit actualy writes to git history. This is a perfect way to automatically call things like `ansible-lint` and `gitleaks` before having to go back and squash or clean up git history.

== Ansible Development Tools (ADT)

Overview, source page: https://ansible.readthedocs.io/projects/dev-tools/

The curated list of tools installed as part of the Ansible automation developer tools package includes:

ansible-core: Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems.

ansible-builder: a utility for building Ansible execution environments.

ansible-creator: a utility for scaffolding Ansible projects and content with leading practices.

ansible-lint: a utility to identify and correct stylistic errors and anti-patterns in Ansible playbooks and roles.

ansible-navigator a text-based user interface (TUI) for developing and troubleshooting Ansible content with execution environments.

ansible-sign: a utility for signing and verifying Ansible content.

molecule: Molecule aids in the development and testing of Ansible content: collections, playbooks and roles

pytest-ansible: a pytest testing framework extension that provides additional functionality for testing Ansible module and plugin Python code.

tox-ansible: an extension to the tox testing utility that provides additional functionality to check Ansible module and plugin Python code under different Python interpreters and Ansible core versions.

ansible-dev-environment: a utility for building and managing a virtual environment for Ansible content development.
